In [1]:
# Dependencies
import numpy as np
import pandas as pd
# Python SQL toolkit and Object Relational Mapper
import sqlalchemy
from sqlalchemy.ext.automap import automap_base
from sqlalchemy.orm import Session
from sqlalchemy import create_engine, func, inspect, Table

In [2]:
engine = create_engine("sqlite:///hawaii.sqlite")

# reflect an existing database into a new model
Base = automap_base()
# reflect the tables
Base.prepare(engine, reflect=True)

# Save references to each table
Measurement = Base.classes.measurement
Station = Base.classes.station

In [3]:
# Create our session (link) from Python to the DB
session = Session(engine)

In [4]:
inspector = inspect(engine)
inspector.get_table_names()

['measurement', 'station']

In [5]:
columns = inspector.get_columns('measurement')
for column in columns:
    print(column['name'], column['type'])

id INTEGER
station TEXT
date TEXT
prcp FLOAT
tobs FLOAT

In [6]:
columns = inspector.get_columns('station')
for column in columns:
    print(column['name'], column['type'])

id INTEGER
station TEXT
name TEXT
latitude FLOAT
longitude FLOAT
elevation FLOAT

## D1: Determine the Summary Statistics for June

In [7]:
# 1. Import the sqlalchemy extract function.
from sqlalchemy import extract
import datetime as dt
# 2. Write a query that filters the Measurement table to retrieve the temperatures for the month of June. 

jun_temps= session.query(Measurement.date, Measurement.tobs).\
    filter(extract('month', Measurement.date)==6)

In [8]:
#  3. Convert the June temperatures to a list.
jun_temps= session.query(Measurement.date, Measurement.tobs).\
    filter(extract('month', Measurement.date)==6).all()

In [9]:
# 4. Create a DataFrame from the list of temperatures for the month of June. 
june_temps_df = pd.DataFrame(jun_temps, columns=['date','tobs'])
june_temps_df

            date  tobs
0     2010-06-01  78.0
1     2010-06-02  76.0
2     2010-06-03  78.0
3     2010-06-04  76.0
4     2010-06-05  77.0
...          ...   ...
1695  2017-06-26  79.0
1696  2017-06-27  74.0
1697  2017-06-28  74.0
1698  2017-06-29  76.0
1699  2017-06-30  75.0

[1700 rows x 2 columns]

In [10]:
# 5. Calculate and print out the summary statistics for the June temperature DataFrame.
june_temps_df.describe()

              tobs
count  1700.000000
mean     74.944118
std       3.257417
min      64.000000
25%      73.000000
50%      75.000000
75%      77.000000
max      85.000000

## D2: Determine the Summary Statistics for December

In [11]:
# 6. Write a query that filters the Measurement table to retrieve the temperatures for the month of December.
dec_temps= session.query(Measurement.date, Measurement.tobs).\
    filter(extract('month', Measurement.date)==12)

In [12]:
# 7. Convert the December temperatures to a list.
dec_temps= session.query(Measurement.date, Measurement.tobs).\
    filter(extract('month', Measurement.date)==12).all()

In [13]:
# 8. Create a DataFrame from the list of temperatures for the month of December. 
dec_df = pd.DataFrame(dec_temps, columns=['date','tobs'])
print(dec_df)

            date  tobs
0     2010-12-01  76.0
1     2010-12-03  74.0
2     2010-12-04  74.0
3     2010-12-06  64.0
4     2010-12-07  64.0
...          ...   ...
1512  2016-12-27  71.0
1513  2016-12-28  71.0
1514  2016-12-29  69.0
1515  2016-12-30  65.0
1516  2016-12-31  65.0

[1517 rows x 2 columns]

In [14]:
# 9. Calculate and print out the summary statistics for the Decemeber temperature DataFrame.
dec_df.describe()

              tobs
count  1517.000000
mean     71.041529
std       3.745920
min      56.000000
25%      69.000000
50%      71.000000
75%      74.000000
max      83.000000

## EXTRA DATA

In [19]:
session.query(Measurement.date, Measurement.tobs).all()

[('2010-01-01', 65.0),
 ('2010-01-02', 63.0),
 ('2010-01-03', 74.0),
 ('2010-01-04', 76.0),
 ('2010-01-06', 73.0),
 ('2010-01-07', 70.0),
 ('2010-01-08', 64.0),
 ('2010-01-09', 68.0),
 ('2010-01-10', 73.0),
 ('2010-01-11', 64.0),
 ('2010-01-12', 61.0),
 ('2010-01-14', 66.0),
 ('2010-01-15', 65.0),
 ('2010-01-16', 68.0),
 ('2010-01-17', 64.0),
 ('2010-01-18', 72.0),
 ('2010-01-19', 66.0),
 ('2010-01-20', 66.0),
 ('2010-01-21', 69.0),
 ('2010-01-22', 67.0),
 ('2010-01-23', 67.0),
 ('2010-01-24', 71.0),
 ('2010-01-25', 67.0),
 ('2010-01-26', 76.0),
 ('2010-01-27', 68.0),
 ('2010-01-28', 72.0),
 ('2010-01-30', 70.0),
 ('2010-01-31', 67.0),
 ('2010-02-01', 66.0),
 ('2010-02-03', 67.0),
 ('2010-02-04', 69.0),
 ('2010-02-05', 67.0),
 ('2010-02-06', 67.0),
 ('2010-02-07', 64.0),
 ('2010-02-08', 69.0),
 ('2010-02-09', 73.0),
 ('2010-02-11', 73.0),
 ('2010-02-12', 69.0),
 ('2010-02-13', 69.0),
 ('2010-02-14', 69.0),
 ('2010-02-15', 71.0),
 ('2010-02-16', 61.0),
 ('2010-02-17', 69.0),
 ('2010-02-19', 63.0),
 ('2010-02-20', 64.0),
 ('2010-02-21', 65.0),
 ('2010-02-22', 67.0),
 ('2010-02-23', 68.0),
 ('2010-02-24', 65.0),
 ('2010-02-25', 76.0),
 ('2010-02-26', 75.0),
 ('2010-02-28', 66.0),
 ('2010-03-01', 70.0),
 ('2010-03-02', 72.0),
 ('2010-03-03', 73.0),
 ('2010-03-04', 70.0),
 ('2010-03-05', 71.0),
 ('2010-03-06', 72.0),
 ('2010-03-07', 72.0),
 ('2010-03-08', 69.0),
 ('2010-03-09', 70.0),
 ('2010-03-11', 73.0),
 ('2010-03-12', 72.0),
 ('2010-03-13', 73.0),
 ('2010-03-14', 70.0),
 ('2010-03-15', 71.0),
 ('2010-03-17', 68.0),
 ('2010-03-18', 70.0),
 ('2010-03-21', 72.0),
 ('2010-03-22', 69.0),
 ('2010-03-23', 68.0),
 ('2010-03-24', 74.0),
 ('2010-03-26', 72.0),
 ('2010-03-27', 72.0),
 ('2010-03-28', 73.0),
 ('2010-03-29', 74.0),
 ('2010-03-30', 73.0),
 ('2010-03-31', 73.0),
 ('2010-04-01', 74.0),
 ('2010-04-02', 74.0),
 ('2010-04-03', 74.0),
 ('2010-04-04', 71.0),
 ('2010-04-05', 72.0),
 ('2010-04-06', 75.0),
 ('2010-04-08', 75.0),
 ('2010-04-09', 75.0),
 ('2010-04-10', 75.0),
 ('2010-04-11', 73.0),
 ('2010-04-12', 73.0),
 ('2010-04-13', 71.0),
 ('2010-04-15', 71.0),
 ('2010-04-16', 68.0),
 ('2010-04-17', 70.0),
 ('2010-04-18', 71.0),
 ('2010-04-19', 74.0),
 ('2010-04-20', 71.0),
 ('2010-04-21', 75.0),
 ('2010-04-22', 76.0),
 ('2010-04-23', 75.0),
 ('2010-04-24', 75.0),
 ('2010-04-25', 76.0),
 ('2010-04-26', 76.0),
 ('2010-04-28', 76.0),
 ('2010-04-30', 77.0),
 ('2010-05-01', 77.0),
 ('2010-05-02', 73.0),
 ('2010-05-03', 74.0),
 ('2010-05-04', 76.0),
 ('2010-05-05', 76.0),
 ('2010-05-06', 80.0),
 ('2010-05-07', 74.0),
 ('2010-05-08', 77.0),
 ('2010-05-09', 77.0),
 ('2010-05-10', 76.0),
 ('2010-05-11', 77.0),
 ('2010-05-13', 78.0),
 ('2010-05-14', 78.0),
 ('2010-05-15', 75.0),
 ('2010-05-16', 73.0),
 ('2010-05-17', 77.0),
 ('2010-05-18', 76.0),
 ('2010-05-19', 77.0),
 ('2010-05-21', 77.0),
 ('2010-05-22', 78.0),
 ('2010-05-23', 75.0),
 ('2010-05-24', 77.0),
 ('2010-05-25', 77.0),
 ('2010-05-26', 77.0),
 ('2010-05-27', 76.0),
 ('2010-05-28', 75.0),
 ('2010-05-29', 77.0),
 ('2010-05-30', 77.0),
 ('2010-05-31', 77.0),
 ('2010-06-01', 78.0),
 ('2010-06-02', 76.0),
 ('2010-06-03', 78.0),
 ('2010-06-04', 76.0),
 ('2010-06-05', 77.0),
 ('2010-06-06', 78.0),
 ('2010-06-07', 77.0),
 ('2010-06-08', 78.0),
 ('2010-06-09', 78.0),
 ('2010-06-10', 79.0),
 ('2010-06-11', 78.0),
 ('2010-06-12', 78.0),
 ('2010-06-13', 78.0),
 ('2010-06-14', 77.0),
 ('2010-06-15', 78.0),
 ('2010-06-16', 78.0),
 ('2010-06-17', 77.0),
 ('2010-06-18', 77.0),
 ('2010-06-19', 82.0),
 ('2010-06-20', 78.0),
 ('2010-06-21', 78.0),
 ('2010-06-22', 78.0),
 ('2010-06-23', 78.0),
 ('2010-06-24', 78.0),
 ('2010-06-25', 77.0),
 ('2010-06-26', 76.0),
 ('2010-06-27', 78.0),
 ('2010-06-28', 78.0),
 ('2010-06-29', 78.0),
 ('2010-06-30', 78.0),
 ('2010-07-01', 75.0),
 ('2010-07-02', 77.0),
 ('2010-07-03', 77.0),
 ('2010-07-04', 78.0),
 ('2010-07-05', 78.0),
 ('2010-07-06', 76.0),
 ('2010-07-07', 74.0),
 ('2010-07-08', 76.0),
 ('2010-07-09', 74.0),
 ('2010-07-10', 76.0),
 ('2010-07-11', 78.0),
 ('2010-07-12', 77.0),
 ('2010-07-13', 80.0),
 ('2010-07-16', 78.0),
 ('2010-07-17', 76.0),
 ('2010-07-18', 77.0),
 ('2010-07-19', 77.0),
 ('2010-07-21', 80.0),
 ('2010-07-22', 78.0),
 ('2010-07-24', 80.0),
 ('2010-07-25', 79.0),
 ('2010-07-26', 78.0),
 ('2010-07-27', 79.0),
 ('2010-07-28', 78.0),
 ('2010-07-29', 79.0),
 ('2010-07-30', 78.0),
 ('2010-07-31', 77.0),
 ('2010-08-01', 77.0),
 ('2010-08-02', 76.0),
 ('2010-08-03', 77.0),
 ('2010-08-04', 77.0),
 ('2010-08-05', 75.0),
 ('2010-08-06', 75.0),
 ('2010-08-07', 80.0),
 ('2010-08-08', 77.0),
 ('2010-08-09', 78.0),
 ('2010-08-10', 78.0),
 ('2010-08-11', 77.0),
 ('2010-08-12', 76.0),
 ('2010-08-13', 78.0),
 ('2010-08-14', 78.0),
 ('2010-08-15', 76.0),
 ('2010-08-16', 76.0),
 ('2010-08-17', 74.0),
 ('2010-08-18', 77.0),
 ('2010-08-19', 79.0),
 ('2010-08-20', 79.0),
 ('2010-08-21', 79.0),
 ('2010-08-22', 75.0),
 ('2010-08-23', 87.0),
 ('2010-08-24', 78.0),
 ('2010-08-25', 76.0),
 ('2010-08-26', 78.0),
 ('2010-08-27', 78.0),
 ('2010-08-28', 79.0),
 ('2010-08-29', 78.0),
 ('2010-08-30', 78.0),
 ('2010-08-31', 80.0),
 ('2010-09-01', 77.0),
 ('2010-09-02', 76.0),
 ('2010-09-03', 78.0),
 ('2010-09-04', 77.0),
 ('2010-09-05', 77.0),
 ('2010-09-06', 77.0),
 ('2010-09-07', 76.0),
 ('2010-09-08', 78.0),
 ('2010-09-09', 78.0),
 ('2010-09-10', 78.0),
 ('2010-09-11', 78.0),
 ('2010-09-12', 74.0),
 ('2010-09-13', 78.0),
 ('2010-09-14', 79.0),
 ('2010-09-15', 77.0),
 ('2010-09-16', 79.0),
 ('2010-09-17', 78.0),
 ('2010-09-19', 78.0),
 ('2010-09-20', 78.0),
 ('2010-09-21', 79.0),
 ('2010-09-22', 76.0),
 ('2010-09-23', 78.0),
 ('2010-09-24', 78.0),
 ('2010-09-25', 79.0),
 ('2010-09-26', 74.0),
 ('2010-09-27', 75.0),
 ('2010-09-28', 75.0),
 ('2010-09-29', 78.0),
 ('2010-09-30', 73.0),
 ('2010-10-01', 78.0),
 ('2010-10-02', 78.0),
 ('2010-10-03', 78.0),
 ('2010-10-04', 78.0),
 ('2010-10-05', 80.0),
 ('2010-10-06', 79.0),
 ('2010-10-07', 79.0),
 ('2010-10-08', 78.0),
 ('2010-10-09', 78.0),
 ('2010-10-10', 78.0),
 ('2010-10-11', 77.0),
 ('2010-10-12', 79.0),
 ('2010-10-13', 78.0),
 ('2010-10-15', 78.0),
 ('2010-10-16', 77.0),
 ('2010-10-17', 76.0),
 ('2010-10-18', 76.0),
 ('2010-10-19', 72.0),
 ('2010-10-20', 74.0),
 ('2010-10-21', 80.0),
 ('2010-10-22', 77.0),
 ('2010-10-23', 75.0),
 ('2010-10-24', 78.0),
 ('2010-10-25', 78.0),
 ('2010-10-26', 76.0),
 ('2010-10-27', 79.0),
 ('2010-10-28', 78.0),
 ('2010-10-29', 78.0),
 ('2010-10-30', 77.0),
 ('2010-10-31', 76.0),
 ('2010-11-01', 75.0),
 ('2010-11-02', 73.0),
 ('2010-11-04', 73.0),
 ('2010-11-05', 77.0),
 ('2010-11-06', 76.0),
 ('2010-11-07', 77.0),
 ('2010-11-08', 76.0),
 ('2010-11-09', 73.0),
 ('2010-11-10', 73.0),
 ('2010-11-11', 77.0),
 ('2010-11-12', 77.0),
 ('2010-11-13', 76.0),
 ('2010-11-16', 73.0),
 ('2010-11-17', 73.0),
 ('2010-11-19', 72.0),
 ('2010-11-20', 69.0),
 ('2010-11-21', 69.0),
 ('2010-11-22', 68.0),
 ('2010-11-23', 69.0),
 ('2010-11-24', 76.0),
 ('2010-11-25', 76.0),
 ('2010-11-27', 75.0),
 ('2010-11-28', 74.0),
 ('2010-11-29', 69.0),
 ('2010-11-30', 74.0),
 ('2010-12-01', 76.0),
 ('2010-12-03', 74.0),
 ('2010-12-04', 74.0),
 ('2010-12-06', 64.0),
 ('2010-12-07', 64.0),
 ('2010-12-08', 67.0),
 ('2010-12-09', 77.0),
 ('2010-12-10', 66.0),
 ('2010-12-11', 69.0),
 ('2010-12-12', 68.0),
 ('2010-12-13', 68.0),
 ('2010-12-14', 71.0),
 ('2010-12-15', 74.0),
 ('2010-12-16', 67.0),
 ('2010-12-17', 66.0),
 ('2010-12-18', 69.0),
 ('2010-12-19', 71.0),
 ('2010-12-23', 70.0),
 ('2010-12-24', 70.0),
 ('2010-12-26', 74.0),
 ('2010-12-27', 74.0),
 ('2010-12-28', 71.0),
 ('2010-12-29', 75.0),
 ('2010-12-30', 75.0),
 ('2010-12-31', 72.0),
 ('2011-01-01', 69.0),
 ('2011-01-02', 72.0),
 ('2011-01-03', 74.0),
 ('2011-01-04', 73.0),
 ('2011-01-05', 64.0),
 ('2011-01-06', 65.0),
 ('2011-01-07', 68.0),
 ('2011-01-08', 62.0),
 ('2011-01-09', 58.0),
 ('2011-01-10', 73.0),
 ('2011-01-11', 60.0),
 ('2011-01-13', 68.0),
 ('2011-01-14', 76.0),
 ('2011-01-15', 68.0),
 ('2011-01-16', 66.0),
 ('2011-01-17', 64.0),
 ('2011-01-18', 64.0),
 ('2011-01-19', 64.0),
 ('2011-01-20', 76.0),
 ('2011-01-21', 75.0),
 ('2011-01-22', 68.0),
 ('2011-01-23', 68.0),
 ('2011-01-24', 72.0),
 ('2011-01-25', 63.0),
 ('2011-01-27', 68.0),
 ('2011-01-28', 75.0),
 ('2011-01-29', 65.0),
 ('2011-01-30', 64.0),
 ('2011-01-31', 68.0),
 ('2011-02-01', 68.0),
 ('2011-02-02', 66.0),
 ('2011-02-03', 67.0),
 ('2011-02-04', 64.0),
 ('2011-02-05', 65.0),
 ('2011-02-06', 75.0),
 ('2011-02-07', 68.0),
 ('2011-02-08', 71.0),
 ('2011-02-09', 71.0),
 ('2011-02-10', 71.0),
 ('2011-02-12', 68.0),
 ('2011-02-13', 68.0),
 ('2011-02-14', 72.0),
 ('2011-02-15', 70.0),
 ('2011-02-16', 74.0),
 ('2011-02-19', 67.0),
 ('2011-02-20', 71.0),
 ('2011-02-21', 71.0),
 ('2011-02-22', 71.0),
 ('2011-02-23', 74.0),
 ('2011-02-24', 68.0),
 ('2011-02-25', 71.0),
 ('2011-02-26', 69.0),
 ('2011-02-27', 69.0),
 ('2011-02-28', 68.0),
 ('2011-03-01', 68.0),
 ('2011-03-02', 72.0),
 ('2011-03-03', 74.0),
 ('2011-03-04', 72.0),
 ('2011-03-05', 69.0),
 ('2011-03-06', 70.0),
 ('2011-03-08', 72.0),
 ('2011-03-09', 71.0),
 ('2011-03-10', 71.0),
 ('2011-03-12', 72.0),
 ('2011-03-13', 70.0),
 ('2011-03-14', 71.0),
 ('2011-03-16', 76.0),
 ('2011-03-17', 73.0),
 ('2011-03-18', 74.0),
 ('2011-03-19', 74.0),
 ('2011-03-20', 74.0),
 ('2011-03-21', 74.0),
 ('2011-03-22', 74.0),
 ('2011-03-23', 74.0),
 ('2011-03-24', 73.0),
 ('2011-03-25', 74.0),
 ('2011-03-26', 74.0),
 ('2011-03-27', 73.0),
 ('2011-03-28', 74.0),
 ('2011-03-30', 75.0),
 ('2011-03-31', 74.0),
 ('2011-04-01', 74.0),
 ('2011-04-02', 75.0),
 ('2011-04-03', 74.0),
 ('2011-04-04', 75.0),
 ('2011-04-05', 74.0),
 ('2011-04-06', 70.0),
 ('2011-04-07', 70.0),
 ('2011-04-08', 70.0),
 ('2011-04-09', 76.0),
 ('2011-04-10', 76.0),
 ('2011-04-11', 76.0),
 ('2011-04-12', 76.0),
 ('2011-04-13', 70.0),
 ('2011-04-15', 77.0),
 ('2011-04-16', 74.0),
 ('2011-04-17', 73.0),
 ('2011-04-18', 76.0),
 ('2011-04-19', 76.0),
 ('2011-04-20', 74.0),
 ('2011-04-21', 77.0),
 ('2011-04-22', 77.0),
 ('2011-04-23', 78.0),
 ('2011-04-24', 77.0),
 ('2011-04-25', 77.0),
 ('2011-04-26', 76.0),
 ('2011-04-27', 77.0),
 ('2011-04-29', 78.0),
 ('2011-04-30', 76.0),
 ('2011-05-01', 77.0),
 ('2011-05-02', 77.0),
 ('2011-05-03', 70.0),
 ('2011-05-04', 76.0),
 ('2011-05-05', 74.0),
 ('2011-05-06', 72.0),
 ('2011-05-07', 74.0),
 ('2011-05-08', 73.0),
 ('2011-05-09', 75.0),
 ('2011-05-10', 75.0),
 ('2011-05-11', 75.0),
 ('2011-05-12', 76.0),
 ('2011-05-13', 77.0),
 ('2011-05-14', 78.0),
 ('2011-05-15', 77.0),
 ('2011-05-16', 78.0),
 ('2011-05-17', 77.0),
 ('2011-05-18', 76.0),
 ('2011-05-19', 77.0),
 ('2011-05-20', 79.0),
 ('2011-05-21', 77.0),
 ('2011-05-22', 74.0),
 ('2011-05-23', 78.0),
 ('2011-05-24', 77.0),
 ('2011-05-25', 79.0),
 ('2011-05-26', 78.0),
 ('2011-05-27', 78.0),
 ('2011-05-28', 77.0),
 ('2011-05-29', 78.0),
 ('2011-05-30', 78.0),
 ('2011-05-31', 73.0),
 ('2011-06-01', 77.0),
 ('2011-06-02', 78.0),
 ('2011-06-03', 73.0),
 ('2011-06-04', 70.0),
 ('2011-06-05', 76.0),
 ('2011-06-06', 77.0),
 ('2011-06-07', 77.0),
 ('2011-06-08', 77.0),
 ('2011-06-09', 77.0),
 ('2011-06-10', 78.0),
 ('2011-06-11', 77.0),
 ('2011-06-12', 77.0),
 ('2011-06-13', 78.0),
 ('2011-06-14', 78.0),
 ('2011-06-15', 77.0),
 ('2011-06-17', 78.0),
 ('2011-06-18', 78.0),
 ('2011-06-19', 75.0),
 ('2011-06-20', 76.0),
 ('2011-06-21', 76.0),
 ('2011-06-24', 77.0),
 ('2011-06-25', 78.0),
 ('2011-06-26', 76.0),
 ('2011-06-27', 77.0),
 ('2011-06-28', 75.0),
 ('2011-06-29', 77.0),
 ('2011-07-01', 77.0),
 ('2011-07-02', 78.0),
 ('2011-07-03', 78.0),
 ('2011-07-04', 78.0),
 ('2011-07-05', 78.0),
 ('2011-07-06', 76.0),
 ('2011-07-07', 76.0),
 ('2011-07-08', 77.0),
 ('2011-07-09', 77.0),
 ('2011-07-10', 77.0),
 ('2011-07-11', 78.0),
 ('2011-07-12', 77.0),
 ('2011-07-13', 73.0),
 ('2011-07-14', 77.0),
 ('2011-07-15', 79.0),
 ('2011-07-16', 78.0),
 ('2011-07-17', 77.0),
 ('2011-07-18', 78.0),
 ('2011-07-19', 78.0),
 ('2011-07-20', 76.0),
 ('2011-07-21', 77.0),
 ('2011-07-23', 78.0),
 ('2011-07-24', 77.0),
 ('2011-07-25', 78.0),
 ('2011-07-26', 78.0),
 ('2011-07-27', 77.0),
 ('2011-07-28', 77.0),
 ('2011-07-29', 78.0),
 ('2011-07-30', 80.0),
 ('2011-07-31', 77.0),
 ('2011-08-01', 78.0),
 ('2011-08-02', 77.0),
 ('2011-08-03', 78.0),
 ('2011-08-04', 76.0),
 ('2011-08-05', 78.0),
 ('2011-08-06', 77.0),
 ('2011-08-07', 78.0),
 ('2011-08-08', 78.0),
 ('2011-08-09', 79.0),
 ('2011-08-11', 78.0),
 ('2011-08-12', 78.0),
 ('2011-08-13', 76.0),
 ('2011-08-14', 78.0),
 ('2011-08-15', 77.0),
 ('2011-08-16', 79.0),
 ('2011-08-17', 77.0),
 ('2011-08-18', 77.0),
 ('2011-08-19', 78.0),
 ('2011-08-20', 77.0),
 ('2011-08-21', 77.0),
 ('2011-08-22', 78.0),
 ('2011-08-23', 78.0),
 ('2011-08-24', 79.0),
 ('2011-08-25', 78.0),
 ('2011-08-26', 78.0),
 ('2011-08-27', 79.0),
 ('2011-08-28', 76.0),
 ('2011-08-29', 76.0),
 ('2011-08-30', 78.0),
 ('2011-08-31', 79.0),
 ('2011-09-02', 79.0),
 ('2011-09-03', 78.0),
 ('2011-09-04', 77.0),
 ('2011-09-05', 77.0),
 ('2011-09-06', 73.0),
 ('2011-09-07', 73.0),
 ('2011-09-08', 77.0),
 ('2011-09-09', 79.0),
 ('2011-09-10', 77.0),
 ('2011-09-11', 77.0),
 ('2011-09-12', 85.0),
 ('2011-09-13', 77.0),
 ('2011-09-14', 76.0),
 ('2011-09-15', 79.0),
 ('2011-09-16', 79.0),
 ('2011-09-17', 77.0),
 ('2011-09-18', 77.0),
 ('2011-09-19', 82.0),
 ('2011-09-20', 80.0),
 ('2011-09-21', 79.0),
 ('2011-09-22', 78.0),
 ('2011-09-23', 76.0),
 ('2011-09-24', 77.0),
 ('2011-09-25', 74.0),
 ('2011-09-26', 77.0),
 ('2011-09-27', 78.0),
 ('2011-09-28', 77.0),
 ('2011-10-01', 78.0),
 ('2011-10-02', 78.0),
 ('2011-10-03', 80.0),
 ('2011-10-05', 79.0),
 ('2011-10-06', 75.0),
 ('2011-10-07', 78.0),
 ('2011-10-08', 79.0),
 ('2011-10-09', 78.0),
 ('2011-10-10', 77.0),
 ('2011-10-11', 78.0),
 ('2011-10-12', 77.0),
 ('2011-10-13', 77.0),
 ('2011-10-14', 78.0),
 ('2011-10-15', 77.0),
 ('2011-10-16', 76.0),
 ('2011-10-17', 77.0),
 ('2011-10-18', 76.0),
 ('2011-10-19', 74.0),
 ('2011-10-20', 78.0),
 ('2011-10-21', 76.0),
 ('2011-10-22', 77.0),
 ('2011-10-23', 75.0),
 ('2011-10-24', 74.0),
 ('2011-10-25', 77.0),
 ('2011-10-26', 76.0),
 ('2011-10-27', 77.0),
 ('2011-10-28', 73.0),
 ('2011-10-29', 76.0),
 ('2011-10-30', 75.0),
 ('2011-10-31', 76.0),
 ('2011-11-01', 71.0),
 ('2011-11-02', 77.0),
 ('2011-11-03', 77.0),
 ('2011-11-04', 75.0),
 ('2011-11-05', 76.0),
 ('2011-11-06', 77.0),
 ('2011-11-07', 78.0),
 ('2011-11-08', 76.0),
 ('2011-11-09', 76.0),
 ('2011-11-10', 76.0),
 ('2011-11-11', 74.0),
 ('2011-11-12', 75.0),
 ('2011-11-13', 76.0),
 ('2011-11-14', 73.0),
 ('2011-11-15', 71.0),
 ('2011-11-16', 75.0),
 ('2011-11-17', 76.0),
 ('2011-11-18', 78.0),
 ('2011-11-19', 76.0),
 ('2011-11-20', 75.0),
 ('2011-11-21', 76.0),
 ('2011-11-22', 73.0),
 ('2011-11-23', 75.0),
 ('2011-11-24', 73.0),
 ('2011-11-25', 70.0),
 ('2011-11-26', 75.0),
 ('2011-11-27', 73.0),
 ('2011-11-28', 72.0),
 ('2011-11-29', 72.0),
 ('2011-11-30', 66.0),
 ('2011-12-01', 69.0),
 ('2011-12-02', 68.0),
 ('2011-12-03', 73.0),
 ('2011-12-04', 74.0),
 ('2011-12-05', 73.0),
 ('2011-12-06', 73.0),
 ('2011-12-07', 73.0),
 ('2011-12-08', 73.0),
 ('2011-12-09', 71.0),
 ('2011-12-10', 73.0),
 ('2011-12-11', 73.0),
 ('2011-12-12', 77.0),
 ('2011-12-13', 72.0),
 ('2011-12-14', 71.0),
 ('2011-12-15', 73.0),
 ('2011-12-16', 70.0),
 ('2011-12-17', 73.0),
 ('2011-12-18', 69.0),
 ('2011-12-19', 74.0),
 ('2011-12-20', 72.0),
 ('2011-12-21', 71.0),
 ('2011-12-22', 72.0),
 ('2011-12-23', 72.0),
 ('2011-12-24', 70.0),
 ('2011-12-25', 73.0),
 ('2011-12-26', 73.0),
 ('2011-12-27', 72.0),
 ('2011-12-28', 73.0),
 ('2011-12-29', 73.0),
 ('2011-12-30', 72.0),
 ('2011-12-31', 63.0),
 ('2012-01-01', 63.0),
 ('2012-01-02', 66.0),
 ('2012-01-03', 66.0),
 ('2012-01-04', 74.0),
 ('2012-01-06', 71.0),
 ('2012-01-07', 65.0),
 ('2012-01-08', 61.0),
 ('2012-01-10', 71.0),
 ('2012-01-11', 65.0),
 ('2012-01-12', 66.0),
 ('2012-01-14', 61.0),
 ('2012-01-15', 74.0),
 ('2012-01-16', 75.0),
 ('2012-01-17', 75.0),
 ('2012-01-18', 75.0),
 ('2012-01-19', 68.0),
 ('2012-01-20', 73.0),
 ('2012-01-21', 74.0),
 ('2012-01-22', 74.0),
 ('2012-01-23', 67.0),
 ('2012-01-24', 66.0),
 ('2012-01-25', 69.0),
 ('2012-01-26', 74.0),
 ('2012-01-27', 68.0),
 ('2012-01-28', 72.0),
 ('2012-01-29', 72.0),
 ('2012-01-30', 71.0),
 ('2012-01-31', 71.0),
 ('2012-02-01', 66.0),
 ('2012-02-02', 72.0),
 ('2012-02-03', 63.0),
 ('2012-02-04', 65.0),
 ('2012-02-05', 69.0),
 ('2012-02-06', 71.0),
 ('2012-02-07', 71.0),
 ('2012-02-08', 65.0),
 ('2012-02-09', 61.0),
 ('2012-02-10', 71.0),
 ('2012-02-11', 72.0),
 ('2012-02-12', 72.0),
 ('2012-02-13', 72.0),
 ('2012-02-14', 65.0),
 ('2012-02-15', 66.0),
 ('2012-02-16', 73.0),
 ('2012-02-17', 73.0),
 ('2012-02-18', 71.0),
 ('2012-02-19', 72.0),
 ('2012-02-20', 73.0),
 ('2012-02-21', 72.0),
 ('2012-02-22', 73.0),
 ('2012-02-23', 77.0),
 ('2012-02-24', 67.0),
 ('2012-02-25', 69.0),
 ('2012-02-26', 73.0),
 ('2012-02-27', 72.0),
 ('2012-02-28', 73.0),
 ('2012-02-29', 74.0),
 ('2012-03-01', 73.0),
 ('2012-03-02', 67.0),
 ('2012-03-03', 71.0),
 ('2012-03-04', 72.0),
 ('2012-03-05', 67.0),
 ('2012-03-06', 69.0),
 ('2012-03-07', 67.0),
 ('2012-03-08', 69.0),
 ('2012-03-09', 66.0),
 ('2012-03-10', 73.0),
 ('2012-03-11', 74.0),
 ('2012-03-12', 71.0),
 ('2012-03-13', 72.0),
 ('2012-03-14', 73.0),
 ('2012-03-15', 71.0),
 ('2012-03-16', 72.0),
 ('2012-03-17', 73.0),
 ('2012-03-18', 72.0),
 ('2012-03-19', 73.0),
 ('2012-03-20', 69.0),
 ('2012-03-21', 73.0),
 ('2012-03-22', 74.0),
 ('2012-03-23', 72.0),
 ('2012-03-24', 74.0),
 ('2012-03-25', 74.0),
 ('2012-03-26', 72.0),
 ('2012-03-27', 70.0),
 ('2012-03-28', 71.0),
 ('2012-03-29', 72.0),
 ('2012-03-30', 73.0),
 ('2012-03-31', 74.0),
 ('2012-04-01', 73.0),
 ('2012-04-02', 74.0),
 ('2012-04-03', 75.0),
 ('2012-04-04', 74.0),
 ('2012-04-05', 74.0),
 ('2012-04-06', 74.0),
 ('2012-04-07', 74.0),
 ('2012-04-08', 74.0),
 ('2012-04-09', 72.0),
 ('2012-04-10', 69.0),
 ('2012-04-11', 71.0),
 ('2012-04-12', 70.0),
 ('2012-04-13', 71.0),
 ('2012-04-14', 70.0),
 ('2012-04-15', 75.0),
 ('2012-04-16', 75.0),
 ('2012-04-17', 75.0),
 ('2012-04-18', 75.0),
 ('2012-04-19', 75.0),
 ('2012-04-20', 75.0),
 ('2012-04-21', 74.0),
 ('2012-04-22', 69.0),
 ('2012-04-23', 73.0),
 ('2012-04-24', 73.0),
 ('2012-04-25', 75.0),
 ('2012-04-26', 74.0),
 ('2012-04-27', 75.0),
 ('2012-04-28', 76.0),
 ('2012-04-29', 75.0),
 ('2012-04-30', 75.0),
 ('2012-05-01', 75.0),
 ('2012-05-02', 75.0),
 ('2012-05-03', 75.0),
 ('2012-05-04', 75.0),
 ('2012-05-05', 74.0),
 ('2012-05-06', 75.0),
 ('2012-05-07', 74.0),
 ('2012-05-08', 75.0),
 ('2012-05-09', 74.0),
 ('2012-05-10', 74.0),
 ('2012-05-11', 75.0),
 ('2012-05-12', 75.0),
 ('2012-05-13', 72.0),
 ('2012-05-14', 74.0),
 ('2012-05-15', 74.0),
 ('2012-05-16', 75.0),
 ('2012-05-17', 76.0),
 ('2012-05-18', 77.0),
 ('2012-05-19', 77.0),
 ('2012-05-20', 77.0),
 ('2012-05-21', 76.0),
 ('2012-05-22', 77.0),
 ('2012-05-23', 76.0),
 ('2012-05-24', 78.0),
 ('2012-05-25', 77.0),
 ('2012-05-26', 76.0),
 ('2012-05-27', 76.0),
 ('2012-05-28', 77.0),
 ('2012-05-29', 76.0),
 ('2012-05-30', 76.0),
 ('2012-05-31', 73.0),
 ('2012-06-01', 76.0),
 ('2012-06-02', 76.0),
 ('2012-06-03', 75.0),
 ('2012-06-04', 77.0),
 ('2012-06-05', 77.0),
 ('2012-06-06', 76.0),
 ('2012-06-07', 78.0),
 ('2012-06-08', 77.0),
 ('2012-06-09', 76.0),
 ('2012-06-10', 77.0),
 ('2012-06-11', 76.0),
 ('2012-06-12', 76.0),
 ('2012-06-13', 77.0),
 ('2012-06-14', 77.0),
 ('2012-06-15', 78.0),
 ('2012-06-16', 77.0),
 ('2012-06-17', 77.0),
 ('2012-06-18', 77.0),
 ('2012-06-19', 76.0),
 ('2012-06-20', 75.0),
 ('2012-06-21', 76.0),
 ('2012-06-22', 76.0),
 ('2012-06-23', 77.0),
 ('2012-06-24', 76.0),
 ('2012-06-25', 73.0),
 ('2012-06-26', 73.0),
 ('2012-06-27', 75.0),
 ('2012-06-28', 77.0),
 ('2012-06-29', 76.0),
 ('2012-06-30', 77.0),
 ('2012-07-01', 76.0),
 ('2012-07-02', 77.0),
 ('2012-07-03', 74.0),
 ('2012-07-04', 77.0),
 ('2012-07-05', 77.0),
 ('2012-07-06', 78.0),
 ('2012-07-07', 76.0),
 ('2012-07-08', 77.0),
 ('2012-07-09', 77.0),
 ('2012-07-10', 76.0),
 ('2012-07-11', 76.0),
 ('2012-07-12', 76.0),
 ('2012-07-13', 77.0),
 ('2012-07-14', 78.0),
 ('2012-07-15', 77.0),
 ('2012-07-16', 78.0),

In [18]:
session.query(Measurement.station, func.count(Measurement.station)).\
group_by(Measurement.station).order_by(func.count(Measurement.station).desc()).all()

[('USC00519281', 2772),
 ('USC00519397', 2724),
 ('USC00513117', 2709),
 ('USC00519523', 2669),
 ('USC00516128', 2612),
 ('USC00514830', 2202),
 ('USC00511918', 1979),
 ('USC00517948', 1372),
 ('USC00518838', 511)]

In [21]:
jun_temps= session.query(Measurement.date, Measurement.tobs).\
    filter(Measurement.station !='USC00518838').\
    filter(Measurement.station !='USC00517948').\
    filter(extract('month', Measurement.date)==6).all()

In [22]:
june_temps_df = pd.DataFrame(jun_temps, columns=['date','tobs'])
june_temps_df

            date  tobs
0     2010-06-01  78.0
1     2010-06-02  76.0
2     2010-06-03  78.0
3     2010-06-04  76.0
4     2010-06-05  77.0
...          ...   ...
1509  2017-06-26  79.0
1510  2017-06-27  74.0
1511  2017-06-28  74.0
1512  2017-06-29  76.0
1513  2017-06-30  75.0

[1514 rows x 2 columns]

In [23]:
june_temps_df.describe()

              tobs
count  1514.000000
mean     74.815720
std       3.253102
min      65.000000
25%      72.000000
50%      75.000000
75%      77.000000
max      85.000000